services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autograder
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network


  web:
    build:
      context: ../
      dockerfile: ./config/Dockerfile
    container_name: web
    restart: unless-stopped
    volumes:
      - ../:/autograder
      - /autograder/autograder/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - db_network
    environment:
      - PROD=false

volumes:
  pgdata:
    name: autograder-pgdata

networks:
  db_network:
    driver: bridge